'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm11
    
    '''<summary>
    '''AdminLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdminLink As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''DrawLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrawLink As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ViewUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewUsers As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ViewUsersEntries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewUsersEntries As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''UserIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserIDText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DrawIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrawIDText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''WinCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WinCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UpdateFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateFilter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView As Global.System.Web.UI.WebControls.GridView
End Class
